### ISSUE TITLE
About outgroup

### ISSUE THREAD

**Issue by Shunsuke-Kanamori** [thamala/PBScan#2]
Dear thamala,

Is the longer the distance to the outgroup, the better for analysis?
Is there any bad influence when the distance to outgroup is small?

Sincerely,
Shunsuke Kanamori

**Comment by thamala** [comment]
The idea is that sites that are under selection in the focal lineage(s) are neutral in the outgroup. If they are too closely related, selection pressure might be similar in all three pops. In general, more distant outgroup is better.

**Comment by Shunsuke-Kanamori** [comment]
Thank you for reply.
I understood that in general, a distant outgroup is preferred and what kind of evolution is the object of detection is also important for outgroup selection.

Thank you again
